// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7-xpRoaNMqK5jNvWqwAFsKN4StCecqeM',
    appId: '1:731841931000:web:d485a85bb96d3c8d7fbd0d',
    messagingSenderId: '731841931000',
    projectId: 'civilia-d6686',
    authDomain: 'civilia-d6686.firebaseapp.com',
    storageBucket: 'civilia-d6686.firebasestorage.app',
    measurementId: 'G-T9V2201R89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkHEtbCFyS3q_Rn8mb9V0Ad0rXGwhIZqs',
    appId: '1:731841931000:android:b7130a64fececb7c7fbd0d',
    messagingSenderId: '731841931000',
    projectId: 'civilia-d6686',
    storageBucket: 'civilia-d6686.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvfXRFguaTYWd3iEav4uPwOIf0A0hgq-M',
    appId: '1:731841931000:ios:580e22cd07f3a1d07fbd0d',
    messagingSenderId: '731841931000',
    projectId: 'civilia-d6686',
    storageBucket: 'civilia-d6686.firebasestorage.app',
    iosBundleId: 'com.example.civilia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvfXRFguaTYWd3iEav4uPwOIf0A0hgq-M',
    appId: '1:731841931000:ios:580e22cd07f3a1d07fbd0d',
    messagingSenderId: '731841931000',
    projectId: 'civilia-d6686',
    storageBucket: 'civilia-d6686.firebasestorage.app',
    iosBundleId: 'com.example.civilia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7-xpRoaNMqK5jNvWqwAFsKN4StCecqeM',
    appId: '1:731841931000:web:0706f74f72391f2b7fbd0d',
    messagingSenderId: '731841931000',
    projectId: 'civilia-d6686',
    authDomain: 'civilia-d6686.firebaseapp.com',
    storageBucket: 'civilia-d6686.firebasestorage.app',
    measurementId: 'G-1MJ9FYZJKB',
  );
}
